//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Members = new HashSet<Member>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public string NameGroupe { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
